# Generated by Django 5.2.2 on 2025-06-07 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_alter_proyecto_descripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='usuario_creado',
            new_name='usuario_crea',
        ),
        migrations.CreateModel(
            name='MiembroProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto')),
                ('usuario_agrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_agrega_a_proyecto', to=settings.AUTH_USER_MODEL)),
                ('usuario_agregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_agregado_a_proyecto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
