# Generated by Django 5.2.2 on 2025-06-07 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_rename_usuario_creado_proyecto_usuario_crea_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembroproyecto',
            name='usuario_agrega',
        ),
    ]
