# Generated by Django 5.2.1 on 2025-06-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0003_tarea_asignado_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='color',
            field=models.CharField(default='verde-malanchite', max_length=30),
        ),
    ]
